export default {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  UPDATED: 'Information updated',
  NOT_UPDATED: 'Information not updated',
  EMAIL_ALREADY_EXIST: 'Email already exist',
  EMAIL_NOT_VERIFIED: 'Email is not verified',
  INVALID_CREDENTIALS: 'Invalid credentials',
  INVALID_INPUT: 'Invalid input',
  INVALID_OTP: 'Invalid otp',
  INVALID_TOKEN: 'Invalid token',
  SESSION_EXPIRED: 'Your session has expired',
  INVALID_EMAIL: 'Invalid email',
  INTERNAL_ERROR: 'Internal Server Error',
  EMAIL_SENT: 'Email sent',
  INVALID_OLD_PASSWORD: 'Invalid old password',
  PASSWORD_UPDATED: 'Password updated successfully',
  PASSWORD_EMAIL_SENT: 'Email sent for updating password',
  PASSWORD_EMAIL_NOT_SENT: 'Email could not be sent for updating password',
  NOT_FOUND: 'Not found',
  INVALID_USER_ID: 'Invalid user id',
  INVALID_ID: 'Invalid id',
  NAME_ALREADY_EXIST: 'Name already exist',
  DEVICE_ID_REQ: 'Device id required',
  UNAUTHORIZED: 'Unauthorized',
  SHOULD_BE_FUTURE_DATE: 'Date must be a future date',
  FILE_SIZE_ERROR: 'File size limit reached',
  OTP_EXPIRE: 'OTP Expired',
  WRONG_PASSWORD: 'Wrong password',
  WRONG_OLD_PASSWORD: 'Old password is wrong',
  LINK_EXPIRE: 'Link has been expired',
  FREE_TRAIL_EXPIRED: 'Free trial has expired.',
  SUB_CATEGORY_NOT_FOUND: 'Sub Category not found',
  CATEGORY_NOT_FOUND: 'Category not found',
  LOGGED_IN: 'Log in successfully.',

};
